### PR TITLE
DEV-14729 & DEV-14295 - Updates minimum terraform and provider versions

### PR DESCRIPTION
**Pull request by souza-dan**
https://datatamr.atlassian.net/browse/DEV-14729
https://datatamr.atlassian.net/browse/DEV-14295

Ran plan for the example, but not apply:
```
var.test_bucket_name
  Name of test S3 bucket name.

  Enter a value: fo1b23to1

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.minimal.module.bucket-iam-policy.data.aws_iam_policy_document.rw_source_policy_doc[0]: Refreshing state...
module.minimal.module.bucket-iam-policy.data.aws_iam_policy_document.ro_source_policy_doc[0]: Refreshing state...
module.minimal.module.bucket-iam-policy.data.aws_iam_policy_document.path_specific_ro_doc[0]: Refreshing state...
module.minimal.module.bucket-iam-policy.data.aws_iam_policy_document.path_specific_rw_doc[0]: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.minimal.module.bucket-iam-policy.aws_iam_policy.ro_policy[0] will be created
  + resource "aws_iam_policy" "ro_policy" {
      + arn       = (known after apply)
      + id        = (known after apply)
      + name      = (known after apply)
      + path      = "/"
      + policy    = jsonencode(
            {
              + Statement = [
                  + {
                      + Action   = [
                          + "s3:List*",
                          + "s3:Get*",
                        ]
                      + Effect   = "Allow"
                      + Resource = [
                          + "arn:aws:s3:::fo1b23to1/path/to/ro-folder/*",
                          + "arn:aws:s3:::fo1b23to1/path/to/ro-folder",
                        ]
                      + Sid      = "ReadOnlyPolicy0"
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + policy_id = (known after apply)
    }

  # module.minimal.module.bucket-iam-policy.aws_iam_policy.rw_policy[0] will be created
  + resource "aws_iam_policy" "rw_policy" {
      + arn       = (known after apply)
      + id        = (known after apply)
      + name      = (known after apply)
      + path      = "/"
      + policy    = jsonencode(
            {
              + Statement = [
                  + {
                      + Action   = [
                          + "s3:PutObjectTagging",
                          + "s3:PutObject",
                          + "s3:ListObjectsV2",
                          + "s3:ListObjects",
                          + "s3:ListMultipartUploadParts",
                          + "s3:ListBucketMultipartUploads",
                          + "s3:ListBucketByTags",
                          + "s3:ListBucket",
                          + "s3:HeadBucket",
                          + "s3:GetObjectVersionForReplication",
                          + "s3:GetObjectVersion",
                          + "s3:GetObjectTagging",
                          + "s3:GetObject",
                          + "s3:GetBucketTagging",
                          + "s3:GetBucketLocation",
                          + "s3:GetBucketCORS",
                          + "s3:DeleteObject",
                        ]
                      + Effect   = "Allow"
                      + Resource = [
                          + "arn:aws:s3:::fo1b23to1/path/to/rw-folder/*",
                          + "arn:aws:s3:::fo1b23to1/path/to/rw-folder",
                        ]
                      + Sid      = "ReadWritePolicy0"
                    },
                  + {
                      + Action   = [
                          + "s3:PutObjectTagging",
                          + "s3:PutObject",
                          + "s3:ListObjectsV2",
                          + "s3:ListObjects",
                          + "s3:ListMultipartUploadParts",
                          + "s3:ListBucketMultipartUploads",
                          + "s3:ListBucketByTags",
                          + "s3:ListBucket",
                          + "s3:HeadBucket",
                          + "s3:GetObjectVersionForReplication",
                          + "s3:GetObjectVersion",
                          + "s3:GetObjectTagging",
                          + "s3:GetObject",
                          + "s3:GetBucketTagging",
                          + "s3:GetBucketLocation",
                          + "s3:GetBucketCORS",
                          + "s3:DeleteObject",
                        ]
                      + Effect   = "Allow"
                      + Resource = [
                          + "arn:aws:s3:::fo1b23to1/path/to/another-rw-folder/*",
                          + "arn:aws:s3:::fo1b23to1/path/to/another-rw-folder",
                        ]
                      + Sid      = "ReadWritePolicy1"
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + policy_id = (known after apply)
    }

  # module.minimal.module.bucket-iam-policy.random_string.rand will be created
  + resource "random_string" "rand" {
      + id          = (known after apply)
      + length      = 6
      + lower       = true
      + min_lower   = 0
      + min_numeric = 0
      + min_special = 0
      + min_upper   = 0
      + number      = true
      + result      = (known after apply)
      + special     = false
      + upper       = true
    }

  # module.minimal.module.encrypted-bucket.aws_s3_bucket.new_bucket will be created
  + resource "aws_s3_bucket" "new_bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "fo1b23to1"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = true
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + server_side_encryption_configuration {
          + rule {
              + apply_server_side_encryption_by_default {
                  + sse_algorithm = "AES256"
                }
            }
        }

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }

  # module.minimal.module.encrypted-bucket.aws_s3_bucket_policy.sse_bucket_policy will be created
  + resource "aws_s3_bucket_policy" "sse_bucket_policy" {
      + bucket = (known after apply)
      + id     = (known after apply)
      + policy = (known after apply)
    }

Plan: 5 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

```

### CODE REVIEW

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Review by daniosim — APPROVED** [review]
👍

**Pull request merged**
